---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
    - name: "ansible-docker-ce"
      branch: "stable"
      become: true
      compose: true
      compose_version: "1.25.5"
