---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu18.04
    image: finaldes/docker-ubuntu-ansible:bionic-20200403
    # pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
