name: Ansible-Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        version:
          - "stable"
          - "edge"
          - "test"
          - "nightly"
        os:
          - ubuntu-18.04
          - windows-2019
      #   python-version:
      #     - 3.6
    steps:
      - uses: actions/checkout@v2.1.0
        # with:
        #   path: molecule_demo
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: pip3 install 'molecule[docker]'
      - name: check molecule exists
        run: molecule --version
      - name: Run docker ${{matrix.version}} test
        run: molecule test --scenario-name ${{matrix.version}}
